### ISSUE TITLE
Demo not working?

### ISSUE THREAD

**Issue by khromov** [jacklenox/WP-Appcache#1]
Hi,

I just tried the demo over at:
http://wp-appcache-demo.haveposts.com/

In both Chrome 38 and Firefox 32, I can't see any cache being utilized. Lookin in developer tools, the page is received from the server every time, and page generation is about 500-700ms.

**Comment by jacklenox** [comment]
Hi there, apologies for this, I've recently been testing a new version of the plugin and right now it's actually disabled on the demo site. It'll be back up shortly.

**Comment by aarontgrogg** [comment]
Seems to still not be working?

Has it been "shortly" yet?  ;-P

Atg

**Comment by jacklenox** [comment]
@aarontgrogg Sorry, I totally lost track of this. This plugin is a total disaster and nobody should use it! :grimacing: I had it pulled from the WP repo and I thought I had updated the README here, but looks as though I didn't. I'm going to do that now.
